image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Dependencies
    command: |
      cd client && npm install
      cd ../server && npm install

  - name: Run Development Servers
    command: |
      cd client && npm run dev & # Run Next.js in the background
      cd ../server && npm run dev # Run Express in the foreground

ports:
  - port: 3000
    onOpen: open-preview # Port for Next.js
  - port: 3001
    onOpen: open-preview # Port for Express

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
